<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="31055" started-at="2017-01-25T12:02:43Z" finished-at="2017-01-25T12:03:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="31055" started-at="2017-01-25T12:02:43Z" finished-at="2017-01-25T12:03:14Z">
      <class name="bahaso.testing.web.Sublesson">
        <test-method status="FAIL" signature="beforeMethod()[pri:0, instance:bahaso.testing.web.Sublesson@47c62251]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-01-25T19:02:43Z" finished-at="2017-01-25T19:02:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at bahaso.testing.webElement.LandingPage.doLogin(LandingPage.java:105)
	at bahaso.testing.web.Sublesson.beforeMethod(Sublesson.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="Simulation2()[pri:0, instance:bahaso.testing.web.Sublesson@47c62251]" name="Simulation2" duration-ms="1" started-at="2017-01-25T19:03:14Z" finished-at="2017-01-25T19:03:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Simulation2 -->
        <test-method status="SKIP" signature="after()[pri:0, instance:bahaso.testing.web.Sublesson@47c62251]" name="after" is-config="true" duration-ms="0" started-at="2017-01-25T19:03:14Z" finished-at="2017-01-25T19:03:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after -->
      </class> <!-- bahaso.testing.web.Sublesson -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
